// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package authmodule.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;
import com.mendix.core.Core;
import java.util.Date;
import javax.crypto.SecretKey;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.security.Keys;

public class JA_GenerateJWT extends UserAction<java.lang.String>
{
	private final java.lang.Long expirySeconds;
	private final authmodule.proxies.ALG_ENUM algorithm;

	public JA_GenerateJWT(
		IContext context,
		java.lang.Long _expirySeconds,
		java.lang.String _algorithm
	)
	{
		super(context);
		this.expirySeconds = _expirySeconds;
		this.algorithm = _algorithm == null ? null : authmodule.proxies.ALG_ENUM.valueOf(_algorithm);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE

// BEGIN USER CODE

String secret = (String) Core.getConfiguration().getConstantValue("AuthModule.JWT_SECRET");

// ❌ Validate expiry
if (expirySeconds == null || expirySeconds <= 0) {
    throw new Exception("ExpirySeconds must be > 0");
}

// ❌ Validate algorithm
if (this.algorithm == null) {
    throw new Exception("Algorithm required");
}

// ⏱️ Time
long now = System.currentTimeMillis();
Date issuedAt = new Date(now);
Date expiry = new Date(now + (expirySeconds * 1000L));

// 🔑 Key
SecretKey key = Keys.hmacShaKeyFor(secret.getBytes());

// 🔥 ENUM SWITCH
io.jsonwebtoken.SignatureAlgorithm algo;

switch (this.algorithm) {
    case HS256:
        algo = io.jsonwebtoken.SignatureAlgorithm.HS256;
        break;
    case HS384:
        algo = io.jsonwebtoken.SignatureAlgorithm.HS384;
        break;
    case HS512:
        algo = io.jsonwebtoken.SignatureAlgorithm.HS512;
        break;
    default:
        throw new Exception("Invalid Algorithm");
}

// 🧾 Generate JWT
String token = Jwts.builder()
    .setIssuedAt(issuedAt)
    .setExpiration(expiry)
    .signWith(key, algo)
    .compact();

// 🎯 FINAL JSON RESPONSE BUILD
String jsonResponse = "{"
    + "\"access_token\":\"" + token + "\","
    + "\"token_type\":\"Bearer\","
    + "\"expires_in\":" + expirySeconds + ","
    + "\"scope\":\"mlx_mulesoft_dev\""
    + "}";

return jsonResponse;

		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_GenerateJWT";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
