// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package authmodule.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.UserAction;
import io.jsonwebtoken.Claims;
import io.jsonwebtoken.ExpiredJwtException;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.security.Keys;
import javax.crypto.SecretKey;
import com.mendix.core.Core;

public class JA_ValidateRequestJWT extends UserAction<java.lang.String>
{
	private final java.lang.String AuthHeader;

	public JA_ValidateRequestJWT(
		IContext context,
		java.lang.String _authHeader
	)
	{
		super(context);
		this.AuthHeader = _authHeader;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
 
// 🔐 Secret
String secret = (String) Core.getConfiguration().getConstantValue("AuthModule.JWT_SECRET");
 
// 🔑 Key
SecretKey key = Keys.hmacShaKeyFor(secret.getBytes());
 
// ❌ Header validation
if (AuthHeader == null || !AuthHeader.startsWith("Bearer ")) {
    return "UNAUTHORIZED - Missing Token";
}
 
// 🎯 Extract token
String token = AuthHeader.substring(7).trim();
 
try {
    // 🔥 STRICT PARSER (NO CLOCK SKEW)
    io.jsonwebtoken.Claims claims = io.jsonwebtoken.Jwts.parserBuilder()
        .setSigningKey(key)
        .setAllowedClockSkewSeconds(0) // 🔥 IMPORTANT
        .build()
        .parseClaimsJws(token)
        .getBody();
 
    // ⏱️ Time check
    long now = System.currentTimeMillis();
    long exp = claims.getExpiration().getTime();
 
    // 🔥 STRICT EXPIRY CHECK
    if (now >= exp) {
        return "TOKEN EXPIRED";
    }
 
    return "SUCCESS";
 
} catch (io.jsonwebtoken.ExpiredJwtException e) {
    return "TOKEN EXPIRED";
} catch (Exception e) {
    return "INVALID TOKEN";
}
 
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_ValidateRequestJWT";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
